### ISSUE TITLE
rrrspec-web doesn't show STDOUT/STDERR

### ISSUE THREAD

**Issue by sauliusgrigaitis** [cookpad/rrrspec#49]
For some reason STDOUT/STDERR is empty. Server just returns json {"stdout":"","stderr":""} . Maybe I misconfigured something?
![2015-06-01-145734_3200x1200_scrot](https://cloud.githubusercontent.com/assets/6917/7912331/34e9a98e-086f-11e5-82ea-8e44902364ee.png)

**Comment by yasaichi** [comment]
@sauliusgrigaitis 
Could you check your config for rrrspec-web?
Perhaps `execute_log_text_path` isn't equal to the one for rrrspec-server :sob: 
If so, you must assign the same values to them.

If you read the following codes, you can understand the reason.
* https://github.com/cookpad/rrrspec/blob/v0.4.2/rrrspec-web/lib/rrrspec/web/api.rb#L62-L63
* https://github.com/cookpad/rrrspec/blob/v0.4.2/rrrspec-server/lib/rrrspec/server/persistent_models.rb#L31
* https://github.com/cookpad/rrrspec/blob/master/rrrspec-server/lib/rrrspec/server/log_file_persister.rb#L28-L44

I hope this can help you :smile:

**Comment by sauliusgrigaitis** [comment]
@yasaichi thanks. Hopefully other peeps will not face this issue at least with default configuration.

**Comment by yasaichi** [comment]
@sauliusgrigaitis 
:+1:
