### ISSUE TITLE
rspec exclusion filter breaks rspec_runner setup 

### ISSUE THREAD

**Issue by jrluis** [cookpad/rrrspec#59]
When using rspec exclusion filter the setup method breaks with a "closed stream" logs.

**How to reproduce:**
In spec_helper.rb add an exclusion filter 'config.filter_run_excluding :disabled => true'
Then add the filter to one example 'it "should pass", :disabled => true do'
Then run the tests using rrrspec

**Call stack:**
closed stream
/usr/local/bundle/gems/rspec-core-3.4.4/lib/rspec/core/formatters/base_text_formatter.rb:23:in `write'
/usr/local/bundle/gems/rspec-core-3.4.4/lib/rspec/core/formatters/base_text_formatter.rb:23:in `puts'
/usr/local/bundle/gems/rspec-core-3.4.4/lib/rspec/core/formatters/base_text_formatter.rb:23:in `message'
/usr/local/bundle/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:189:in `block in notify'
/usr/local/bundle/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:188:in `each'
/usr/local/bundle/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:188:in `notify'
/usr/local/bundle/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:95:in `message'
/usr/local/bundle/gems/rspec-core-3.4.4/lib/rspec/core/world.rb:156:in `report_filter_message'
/usr/local/bundle/gems/rspec-core-3.4.4/lib/rspec/core/world.rb:132:in `announce_filters'
/usr/local/bundle/gems/rrrspec-client-0.4.2/lib/rrrspec/client/rspec_runner.rb:38:in `block in setup'
/usr/local/bundle/gems/rrrspec-client-0.4.2/lib/rrrspec/client/rspec_runner.rb:20:in `exc_safe_replace_stdouts'
/usr/local/bundle/gems/rrrspec-client-0.4.2/lib/rrrspec/client/rspec_runner.rb:33:in `setup'
/usr/local/bundle/gems/rrrspec-client-0.4.2/lib/rrrspec/client/slave_runner.rb:62:in `work'
/usr/local/bundle/gems/rrrspec-client-0.4.2/lib/rrrspec/client/slave_runner.rb:28:in `block in work_loop'
/usr/local/bundle/gems/rrrspec-client-0.4.2/lib/rrrspec/client/slave_runner.rb:28:in `loop'
/usr/local/bundle/gems/rrrspec-client-0.4.2/lib/rrrspec/client/slave_runner.rb:28:in `work_loop'
/usr/local/bundle/gems/rrrspec-client-0.4.2/lib/rrrspec/client/cli.rb:147:in `block (2 levels) in slave'`

**Comment by yasaichi** [comment]
I faced the same problem when I only added the exclusion filter to `spec_helper.rb`.
The STDERR is as follows.

```
RSpec's reporter has already been initialized with #<IO:<STDOUT>> as the output stream, so your change to `output_stream` will be ignored. You should configure it earlier for it to take effect. (Called from /path/to/rrrspec-client-0.4.2/lib/rrrspec/client/rspec_runner.rb:57:in `block in run')
```

As I looked over rspec-core code, This message seems generated at https://github.com/rspec/rspec-core/blob/v3.4.0/lib/rspec/core/configuration.rb#L220 .

**Comment by eagletmt** [comment]
Could you try this branch? https://github.com/cookpad/rrrspec/tree/fix-output-stream
I will also test the branch in our environment.

**Comment by jrluis** [comment]
Tested ok, #60 fixed this issue. 
Closing issue
