### ISSUE TITLE
Anyway to send message when a TaskSet finished from rrrspec-server?

### ISSUE THREAD

**Issue by huytv593** [cookpad/rrrspec#69]
When my TaskSet finished, I want to receive notify in other places (like Slack, Telegram, Github, etc). How can I add my custom code to send a message?
I tried to use cronjob to get Taskset's info from rrrspec-web api and it's worked. But I'm trying to find another way to automatically send it from rrrspec-server.
Thanks for your help in advance!

**Comment by eagletmt** [comment]
`rrrspec waitfor $TASKSET_KEY` command waits for the TaskSet's finish by polling. You can also modify the polling interval by `--pollsec=`.
Is this what you want?

```sh
TASKSET_KEY=$(rrrspec start --key-only)
notify-to-somewhere "$TASKSET_KEY is enqueued"
rrrspec waitfor $TASKSET_KEY --pollsec=10
notify-to-somewhere "$TASKSET_KEY finished"
```

**Comment by huytv593** [comment]
@eagletmt It looks like cron job way. I'm finding another way. 
I saw in the `Arbiter` we use `update_status` to set the final status. I may want to push message from this function: After set the final status (failed, succeeded, canceled)

Sorry for the late reply & thanks for your help.
